### PR TITLE
Fix jira URL prefixes to work with new jira boards

### LINKED ISSUE #195: Support backlog & board view of JIRA next gen software projects
JIRA has a new type of project which we do not yet support fully:

https://confluence.atlassian.com/jirasoftwarecloud/working-with-next-gen-software-projects-945104895.html

An example is e.g. our own bchp board: 
https://bitcrowd.atlassian.net/jira/software/projects/BCHP/boards/7

Both views currently make tickety-tick error out: 

Screenshot 2019-11-28 at 18 47 10

### PR DESCRIPTION
**Pull request by tessi**
The JIRA board URLS changed for new JIRA boards. They now contain
optional trailing slashes and also allow further nested routes.
Examples:

* `/jira/software/projects/ABCD/boards/7`
* `/jira/software/projects/ABCD/boards/7/backlog`

Where before, only this URL was recognized:

* `/jira/software/projects/BCHP/boards/7/`

Closes #195.

### CODE REVIEW

File: src/common/adapters/jira.js [hunk 1]
```diff
@@ -19,7 +19,10 @@ function isJiraPage(loc, doc) {
   return false;
 }
 
-const pathSuffixes = new RegExp('/(browse/[^/]+|projects/[^/]+/issues/[^/]+|secure/RapidBoard.jspa|jira/software/projects/[^/]+/boards/[^/]+/)$', 'g');
+const pathSuffixes = new RegExp(
+  '/(browse/[^/]+|projects/[^/]+/issues/[^/]+|secure/RapidBoard.jspa|jira/software/projects/[^/]+/boards/.*)$',
```
Comment (tessi) [inline src/common/adapters/jira.js:23]: `jira/software/projects/[^/]+/boards/.*` captures all possible trailing URL parts of the board view. I opted to not be very specific here and just catch all possible routes within `/boards/` to be more stable against further JIRA changes.

**Comment by pmeinhardt** [comment]
Is this a different problem from: https://github.com/bitcrowd/tickety-tick/pull/216?

**Comment by tessi** [comment]
> Is this a different problem from: #216?

This is the exact issue i fixed - by not scanning (and removing) the prefix path correctly that weird URL from #216 gets built.

**Comment by tessi** [comment]
@pmeinhardt true that, added tests. Actually one of the existing tests passed although the wrong jira base_url was called. I added a check against which API URL is called to the relevant tests.

File: src/common/adapters/jira.js (hunk 1 above)
Comment (pmeinhardt) [reply src/common/adapters/jira.js:23]: Cool. This should also cover what we had here: https://github.com/bitcrowd/tickety-tick/pull/216/files#diff-a4549fad9112b44c628079812d266381L22-R22
